- name: Add Docker gpg key to system
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    validate_certs: false
  tags:
    - docker_install

- name: Add docker repository
  apt_repository:
    filename: docker
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_facts.distribution_release}} stable"
    update_cache: true
    validate_certs: false
  tags:
    - docker_install

- name: Apt update and Install Dependencies
  apt:
    allow_unauthenticated: true
    force_apt_get: true
    install_recommends: true
    name: "{{ package }}"
    state: latest
    update_cache: true
  loop: ["python3-pip","docker-ce","docker-ce-cli","containerd.io","jq"]
  loop_control:
    loop_var: package
  tags:
    - docker_install

- name: Apt clean and remove unnecessary dependencies
  apt:
    autoclean: true
    autoremove: true
  tags:
    - docker_install

- name: Enable docker for auto start
  systemd:
    enabled: true
    name: docker
    state: started
  tags:
    - docker_install

- name: Add current user to docker group
  user:
    name: "{{ansible_user}}"
    groups: docker
    append: yes
  become: yes
  tags:
    - docker_install

- name: Link python3 as default python
  file:
    src: /usr/bin/python3
    path: /usr/bin/python
    state: hard
    force: true

- name: Link pip3 as default pip
  file:
    src: /usr/bin/pip3
    path: /usr/bin/pip
    state: hard

- name: Necessary Pip packages
  pip:
    name: "{{ pip_pack }}"
    state: latest
  loop: ["pip","docker-compose"]
  loop_control:
    loop_var: pip_pack
  tags:
    - docker_compose_install

- name: Add docker daemon config
  json_data:
    path: "/etc/docker/daemon.json"
    values: >
                {
                   "exec-opts": ["native.cgroupdriver=systemd","LimitNOFILE=1048576","LimitNPROC=infinity","LimitCORE=infinity","TasksMax=infinity","TimeoutStartSec=0","Delegate=yes","KillMode=process","Restart=on-failure","StartLimitBurst=3"],
                   "max-concurrent-downloads":30,
                   "max-concurrent-uploads":30,
                   "storage-driver":"overlay2",
                   "log-driver":"json-file",
                   "log-opts":{
                      "max-size":"10m",
                      "max-file":"30",
                      "labels":"production"
                   }
                }
  notify:
    - Restart docker
  tags:
    - docker_install
