---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: demo-ops
spec:
  selector:
    service: app
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer # change to NodePort if you are deploying to localcluster.
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo-ops
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
  type: ClusterIP
  clusterIP: None # headless service
